/// Schema-guided JSON constrained decoding via prefix FST.
///
/// Generates one of a fixed set of JSON templates. At each byte position,
/// only bytes that continue at least one valid template are allowed.
/// Value positions (marked with `\x00` in templates) allow any printable byte.
///
/// This is equivalent to a union of string automata with wildcard holes.

/// Placeholder byte in templates — matches any printable non-quote byte.
const WILD: u8 = 0x00;

/// Build the set of template prefixes for all tool schemas.
/// Each template is a byte sequence like:
///   `{"tool": "dispatch_task", "project": "\x00", "prompt": "\x00"}`
/// where `\x00` positions accept any printable byte.
pub fn build_templates() -> Vec<Vec<u8>> {
    vec![
        template(r#"{"tool": "gmail_search", "query": ""#, &[WILD], r#""}"#, &[], r#""#),
        template(r#"{"tool": "calendar_events", "days": ""#, &[WILD], r#""}"#, &[], r#""#),
        template(r#"{"tool": "calendar_search", "query": ""#, &[WILD], r#""}"#, &[], r#""#),
        template(r#"{"tool": "drive_list"}"#, &[], r#""#, &[], r#""#),
        template(r#"{"tool": "drive_search", "query": ""#, &[WILD], r#""}"#, &[], r#""#),
        template(r#"{"tool": "escalate", "query": ""#, &[WILD], r#""}"#, &[], r#""#),
    ]
}

fn template(prefix: &str, wild1: &[u8], mid: &str, wild2: &[u8], suffix: &str) -> Vec<u8> {
    let mut t = Vec::new();
    t.extend(prefix.as_bytes());
    t.extend(wild1);
    t.extend(mid.as_bytes());
    t.extend(wild2);
    t.extend(suffix.as_bytes());
    t
}

/// Schema FST — tracks position in the template set.
#[derive(Clone)]
pub struct SchemaFST {
    templates: Vec<Vec<u8>>,
    pos: usize,
    /// For each template, whether it's still a valid candidate.
    alive: Vec<bool>,
    /// Currently inside a WILD section (free value).
    in_wild: bool,
}

impl SchemaFST {
    pub fn new() -> Self {
        let templates = build_templates();
        let alive = vec![true; templates.len()];
        Self { templates, pos: 0, alive, in_wild: false }
    }

    /// Allowed bytes inside WILD (value) sections: ASCII alphanumeric + safe special chars + closing quote.
    /// Deliberately excludes { } [ ] < > to prevent the model from generating nested structures.
    fn wild_allowed() -> &'static [u8] {
        // a-z A-Z 0-9 - _ . / : ~ + = , ; @ ! ? # % & * ( ) ' space " (closing quote)
        static ALLOWED: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./:~+=,;@!?#%&*() '\"";
        ALLOWED
    }

    /// Which bytes are valid at the current position.
    /// In wild sections, returns constrained ASCII set (not unconstrained).
    pub fn valid_next_bytes(&self) -> Option<Vec<u8>> {
        if self.in_wild {
            return Some(Self::wild_allowed().to_vec());
        }

        let mut valid = Vec::new();
        let mut has_wild = false;
        for (i, tmpl) in self.templates.iter().enumerate() {
            if !self.alive[i] { continue; }
            if self.pos >= tmpl.len() { continue; }
            let b = tmpl[self.pos];
            if b == WILD {
                has_wild = true;
                continue;
            }
            if !valid.contains(&b) {
                valid.push(b);
            }
        }

        if has_wild {
            // At least one template enters wild here — allow wild chars + any literal continuations
            let mut merged = Self::wild_allowed().to_vec();
            for b in &valid {
                if !merged.contains(b) { merged.push(*b); }
            }
            Some(merged)
        } else if valid.is_empty() {
            None // all dead
        } else {
            Some(valid)
        }
    }

    /// Convert to a Constraint for the GPU gate.
    /// Never returns AnyCharacter — when all templates die, returns a bitmap
    /// that only allows `}` and `"` (to close the JSON gracefully).
    pub fn constraint(&self) -> crate::json_sampler::Constraint {
        match self.valid_next_bytes() {
            None => {
                // All templates dead — only allow } to close the JSON
                crate::json_sampler::Constraint::byte(b'}')
            }
            Some(bytes) => {
                let mut w = [0u32; 4];
                for b in bytes {
                    if b < 128 {
                        let bit = 1u32 << (b & 31);
                        w[(b >> 5) as usize] |= bit;
                    }
                }
                crate::json_sampler::Constraint::JsonBitmap(w)
            }
        }
    }

    /// Advance by one generated byte.
    pub fn advance(&mut self, b: u8) {
        if self.in_wild {
            // In a free value section — exit when we see closing quote
            if b == b'"' {
                self.in_wild = false;
                self.pos += 1; // skip past the WILD marker
                // Now advance past the `"` in the template too
                // The template has WILD followed by `"` — we consumed `"`, advance
                // Filter alive templates at the new position
                for (i, tmpl) in self.templates.iter().enumerate() {
                    if !self.alive[i] { continue; }
                    // After WILD, the next byte in template should be what follows WILD
                    // We already advanced pos past WILD, check current pos
                    if self.pos < tmpl.len() && tmpl[self.pos] != b'"' {
                        // Mismatch — this template expected something else after the wild value
                        // Actually the `"` closing the value is part of the template text after WILD
                    }
                }
                // The `"` is the closing quote of the value — it's implicit after WILD
                // Templates: ...WILD..."  — the `"` after WILD is in the template
                // We need to skip past it in the template
                self.advance_templates(b);
            }
            return;
        }

        // Check if any alive template has WILD at this position
        for (i, tmpl) in self.templates.iter().enumerate() {
            if !self.alive[i] { continue; }
            if self.pos < tmpl.len() && tmpl[self.pos] == WILD {
                if b == b'"' {
                    // Empty value ("") — closing quote immediately
                    // Skip past WILD and match the closing quote
                    self.pos += 1;
                    self.advance_templates(b);
                } else {
                    // Enter wild mode — this byte is the start of a free value
                    self.in_wild = true;
                    // Don't advance pos — stay at WILD until closing quote
                }
                return;
            }
        }

        self.advance_templates(b);
    }

    fn advance_templates(&mut self, b: u8) {
        for (i, tmpl) in self.templates.iter().enumerate() {
            if !self.alive[i] { continue; }
            if self.pos >= tmpl.len() || tmpl[self.pos] != b {
                self.alive[i] = false;
            }
        }
        self.pos += 1;
    }

    /// Are all templates exhausted?
    pub fn is_done(&self) -> bool {
        self.alive.iter().enumerate().all(|(i, &a)| {
            !a || self.pos >= self.templates[i].len()
        })
    }

    /// Is the FST still active (at least one template alive)?
    pub fn is_active(&self) -> bool {
        self.alive.iter().any(|&a| a)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Drive the FST through a full byte sequence, asserting it stays active
    /// and each byte is in the valid set. Returns the FST state after.
    fn drive(input: &[u8]) -> SchemaFST {
        let mut fst = SchemaFST::new();
        for (i, &b) in input.iter().enumerate() {
            assert!(fst.is_active(), "FST died at pos {} byte {:?}", i, b as char);
            if let Some(ref v) = fst.valid_next_bytes() {
                assert!(v.contains(&b),
                    "byte {:?} (0x{:02x}) not in valid set ({} options) at pos {}",
                    b as char, b, v.len(), i);
            }
            fst.advance(b);
        }
        fst
    }

    /// Assert the FST rejects a full byte sequence (dies before end).
    fn drive_rejects(input: &[u8]) {
        let mut fst = SchemaFST::new();
        for &b in input {
            if !fst.is_active() { return; } // died — rejected
            if let Some(ref v) = fst.valid_next_bytes() {
                if !v.contains(&b) { return; } // byte blocked — rejected
            }
            fst.advance(b);
        }
        // If we get here, also check: is it done? If not, still "alive but incomplete" is ok
        // The test expectation is that the FST rejects — so if it's still active, that's a failure
        // unless the sequence was truncated.
    }

    // ── Prefix disambiguation ──────────────────────────────────────────

    #[test]
    fn test_dispatch_task_prefix() {
        let fst = drive(b"{\"tool\": \"d");
        // After "d", only "ispatch_task" should be alive
        let valid = fst.valid_next_bytes().unwrap();
        assert_eq!(valid, vec![b'i']);
    }

    #[test]
    fn test_tool_name_branching() {
        // After {"tool": " multiple tool names are valid
        let fst = drive(br#"{"tool": ""#);
        let valid = fst.valid_next_bytes().unwrap();
        // Should contain first chars of all tool names: d, s, c, p, r, e, l, f
        for ch in [b'd', b's', b'c', b'p', b'r', b'e', b'l', b'f'] {
            assert!(valid.contains(&ch),
                "expected '{}' in valid set after tool name open quote", ch as char);
        }
    }

    #[test]
    fn test_execute_vs_escalate_branching() {
        // Both start with "e" — after "ex" should narrow to execute_coder_plan
        // After "es" should narrow to escalate_to_oracle
        let fst_ex = drive(br#"{"tool": "ex"#);
        let v = fst_ex.valid_next_bytes().unwrap();
        assert!(v.contains(&b'e'), "should continue with 'e' for 'execute'");

        let fst_es = drive(br#"{"tool": "es"#);
        let v = fst_es.valid_next_bytes().unwrap();
        assert!(v.contains(&b'c'), "should continue with 'c' for 'escalate'");
    }

    // ── Full tool call sequences (all 9 templates) ─────────────────────

    #[test]
    fn full_dispatch_task() {
        let fst = drive(br#"{"tool": "dispatch_task", "project": "my-proj", "prompt": "do stuff"}"#);
        assert!(fst.is_done(), "dispatch_task should be complete");
    }

    #[test]
    fn full_submit_project_ticket() {
        let fst = drive(br#"{"tool": "submit_project_ticket", "project": "htc-kernel", "prompt": "git remote"}"#);
        assert!(fst.is_done(), "submit_project_ticket should be complete");
    }

    #[test]
    fn full_create_coder_project() {
        let fst = drive(br#"{"tool": "create_coder_project", "name": "test-proj"}"#);
        assert!(fst.is_done(), "create_coder_project should be complete");
    }

    #[test]
    fn full_plan_coder_task() {
        let fst = drive(br#"{"tool": "plan_coder_task", "project": "chitin", "prompt": "add auth"}"#);
        assert!(fst.is_done(), "plan_coder_task should be complete");
    }

    #[test]
    fn full_refine_coder_plan() {
        let fst = drive(br#"{"tool": "refine_coder_plan", "project": "chitin", "prompt": "add error handling"}"#);
        assert!(fst.is_done(), "refine_coder_plan should be complete");
    }

    #[test]
    fn full_execute_coder_plan() {
        let fst = drive(br#"{"tool": "execute_coder_plan", "project": "chitin"}"#);
        assert!(fst.is_done(), "execute_coder_plan should be complete");
    }

    #[test]
    fn full_list_entities() {
        let fst = drive(br#"{"tool": "list_entities", "type": "project"}"#);
        assert!(fst.is_done(), "list_entities should be complete");
    }

    #[test]
    fn full_find_entity() {
        let fst = drive(br#"{"tool": "find_entity", "name": "alpha", "type": "project"}"#);
        assert!(fst.is_done(), "find_entity should be complete");
    }

    #[test]
    fn full_escalate_to_oracle() {
        let fst = drive(br#"{"tool": "escalate_to_oracle", "query": "what is a cat"}"#);
        assert!(fst.is_done(), "escalate_to_oracle should be complete");
    }

    // ── Wild section behavior ──────────────────────────────────────────

    #[test]
    fn wild_allows_special_chars() {
        // Value fields should accept dashes, underscores, slashes, spaces
        let fst = drive(br#"{"tool": "escalate_to_oracle", "query": "how does TCP/IP work?"}"#);
        assert!(fst.is_done());
    }

    #[test]
    fn wild_allows_numbers_and_mixed() {
        let fst = drive(br#"{"tool": "dispatch_task", "project": "proj-v2.1", "prompt": "check build #42"}"#);
        assert!(fst.is_done());
    }

    #[test]
    fn empty_value_string() {
        // Empty string "" in a wild section — closing quote immediately
        let fst = drive(br#"{"tool": "list_entities", "type": ""}"#);
        assert!(fst.is_done(), "empty value should be accepted");
    }

    #[test]
    fn empty_values_multi_field() {
        // Both fields empty
        let fst = drive(br#"{"tool": "dispatch_task", "project": "", "prompt": ""}"#);
        assert!(fst.is_done(), "both empty values should be accepted");
    }

    #[test]
    fn single_char_value() {
        let fst = drive(br#"{"tool": "list_entities", "type": "x"}"#);
        assert!(fst.is_done());
    }

    #[test]
    fn long_value_string() {
        let long_val = "a]".repeat(50); // no braces/brackets in wild
        let input = format!(r#"{{"tool": "escalate_to_oracle", "query": "{}"}}"#,
            &long_val[..long_val.len()-1]); // trim trailing ]
        // Just test it doesn't crash; value with ] not allowed in wild
        // Use a clean long value instead
        let safe = "a".repeat(100);
        let input = format!(r#"{{"tool": "escalate_to_oracle", "query": "{}"}}"#, safe);
        let fst = drive(input.as_bytes());
        assert!(fst.is_done());
    }

    // ── Constraint enforcement ─────────────────────────────────────────

    #[test]
    fn blocks_premature_close_after_tool_name() {
        let fst = drive(br#"{"tool": "dispatch_task""#);
        let valid = fst.valid_next_bytes().unwrap();
        assert!(valid.contains(&b','), "comma should be valid");
        assert!(!valid.contains(&b'}'), "}} should NOT be valid — required fields remain");
    }

    #[test]
    fn blocks_premature_close_mid_object() {
        // After first field, second field is required
        let fst = drive(b"{\"tool\": \"dispatch_task\", ");
        let valid = fst.valid_next_bytes();
        if let Some(v) = valid {
            assert!(!v.contains(&b'}'), "}} not allowed — project field required");
        }
    }

    #[test]
    fn blocks_wrong_key_name() {
        // After dispatch_task, the next key must be "project" — "foo" should kill it
        let mut fst = SchemaFST::new();
        let prefix = br#"{"tool": "dispatch_task", "foo"#;
        for &b in prefix {
            if !fst.is_active() { break; }
            fst.advance(b);
        }
        // FST should be dead or "f" should have been rejected
        // (since valid next after comma+space+" is "p" for "project")
    }

    #[test]
    fn constraint_forces_structural_bytes() {
        // At position 0, only { is valid
        let fst = SchemaFST::new();
        let valid = fst.valid_next_bytes().unwrap();
        assert_eq!(valid, vec![b'{'], "first byte must be {{");
    }

    #[test]
    fn constraint_at_key_quote() {
        // After {, only " is valid (start of "tool" key)
        let fst = drive(b"{");
        let valid = fst.valid_next_bytes().unwrap();
        assert!(valid.contains(&b'"'), "must start key with quote");
    }

    // ── Dead schema behavior ───────────────────────────────────────────

    #[test]
    fn dead_schema_forces_close_brace() {
        let mut fst = SchemaFST::new();
        // Feed something that kills all templates
        for &b in b"{\"tool\": \"ZZZZ" {
            fst.advance(b);
        }
        assert!(!fst.is_active(), "no template starts with ZZZZ");
        let c = fst.constraint();
        // Should force } only
        assert!(c.allows(b'}'), "dead schema must allow }}");
        assert!(!c.allows(b'"'), "dead schema must not allow other chars");
        assert!(!c.allows(b'a'), "dead schema must not allow letters");
    }

    #[test]
    fn dead_schema_valid_next_bytes_is_none() {
        let mut fst = SchemaFST::new();
        for &b in b"{\"tool\": \"ZZZZ" {
            fst.advance(b);
        }
        assert!(fst.valid_next_bytes().is_none(), "dead schema returns None");
    }

    // ── Multi-template alive simultaneously ────────────────────────────

    #[test]
    fn multiple_templates_alive_at_tool_prefix() {
        // "plan_coder_task" and "plan_..." — only plan_coder_task starts with "plan"
        // but "p" also matches "project" in submit_project_ticket at different position
        // After full tool prefix, check alive count
        let fst = drive(br#"{"tool": ""#);
        let alive_count = fst.alive.iter().filter(|&&a| a).count();
        assert_eq!(alive_count, fst.templates.len(), "all templates alive at tool name start");
    }

    #[test]
    fn narrows_to_two_field_tools() {
        // After "dispatch_task", only dispatch_task template alive
        let fst = drive(br#"{"tool": "dispatch_task""#);
        let alive_count = fst.alive.iter().filter(|&&a| a).count();
        assert_eq!(alive_count, 1, "only dispatch_task should survive");
    }

    #[test]
    fn list_and_execute_both_single_field() {
        // list_entities and execute_coder_plan both have single WILD + }
        // After "l" only list_entities; after "execute" only execute_coder_plan
        let fst_l = drive(br#"{"tool": "l"#);
        let alive: Vec<usize> = fst_l.alive.iter().enumerate()
            .filter(|(_, &a)| a).map(|(i, _)| i).collect();
        assert_eq!(alive.len(), 1, "only list_entities starts with 'l'");

        let fst_exec = drive(br#"{"tool": "execute"#);
        let alive: Vec<usize> = fst_exec.alive.iter().enumerate()
            .filter(|(_, &a)| a).map(|(i, _)| i).collect();
        assert_eq!(alive.len(), 1, "only execute_coder_plan starts with 'execute'");
    }
}
