/// Schema-guided JSON constrained decoding via prefix FST.
///
/// Generates one of a fixed set of JSON templates. At each byte position,
/// only bytes that continue at least one valid template are allowed.
/// Value positions (marked with `\x00` in templates) allow any printable byte.
///
/// This is equivalent to a union of string automata with wildcard holes.

/// Placeholder byte in templates — matches any printable non-quote byte.
const WILD: u8 = 0x00;

/// Build the set of template prefixes for all tool schemas.
/// Each template is a byte sequence like:
///   `{"tool": "dispatch_task", "project": "\x00", "prompt": "\x00"}`
/// where `\x00` positions accept any printable byte.
pub fn build_templates() -> Vec<Vec<u8>> {
    vec![
        template(r#"{"tool": "dispatch_task", "project": ""#, &[WILD], r#"", "prompt": ""#, &[WILD], r#""}"#),
        template(r#"{"tool": "submit_project_ticket", "project": ""#, &[WILD], r#"", "prompt": ""#, &[WILD], r#""}"#),
        template(r#"{"tool": "create_coder_project", "name": ""#, &[WILD], r#""}"#, &[], r#""#),
        template(r#"{"tool": "plan_coder_task", "project": ""#, &[WILD], r#"", "prompt": ""#, &[WILD], r#""}"#),
        template(r#"{"tool": "list_entities", "type": ""#, &[WILD], r#""}"#, &[], r#""#),
        template(r#"{"tool": "find_entity", "name": ""#, &[WILD], r#"", "type": ""#, &[WILD], r#""}"#),
        template(r#"{"tool": "escalate_to_oracle", "query": ""#, &[WILD], r#""}"#, &[], r#""#),
    ]
}

fn template(prefix: &str, wild1: &[u8], mid: &str, wild2: &[u8], suffix: &str) -> Vec<u8> {
    let mut t = Vec::new();
    t.extend(prefix.as_bytes());
    t.extend(wild1);
    t.extend(mid.as_bytes());
    t.extend(wild2);
    t.extend(suffix.as_bytes());
    t
}

/// Schema FST — tracks position in the template set.
#[derive(Clone)]
pub struct SchemaFST {
    templates: Vec<Vec<u8>>,
    pos: usize,
    /// For each template, whether it's still a valid candidate.
    alive: Vec<bool>,
    /// Currently inside a WILD section (free value).
    in_wild: bool,
}

impl SchemaFST {
    pub fn new() -> Self {
        let templates = build_templates();
        let alive = vec![true; templates.len()];
        Self { templates, pos: 0, alive, in_wild: false }
    }

    /// Allowed bytes inside WILD (value) sections: ASCII alphanumeric + common special chars + closing quote.
    fn wild_allowed() -> &'static [u8] {
        // a-z A-Z 0-9 - _ . / : ~ + = , ; @ ! ? # % & * ( ) [ ] { } ' < > space " (closing quote)
        static ALLOWED: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./:~+=,;@!?#%&*()[]{}' <>\"";
        ALLOWED
    }

    /// Which bytes are valid at the current position.
    /// In wild sections, returns constrained ASCII set (not unconstrained).
    pub fn valid_next_bytes(&self) -> Option<Vec<u8>> {
        if self.in_wild {
            return Some(Self::wild_allowed().to_vec());
        }

        let mut valid = Vec::new();
        let mut has_wild = false;
        for (i, tmpl) in self.templates.iter().enumerate() {
            if !self.alive[i] { continue; }
            if self.pos >= tmpl.len() { continue; }
            let b = tmpl[self.pos];
            if b == WILD {
                has_wild = true;
                continue;
            }
            if !valid.contains(&b) {
                valid.push(b);
            }
        }

        if has_wild {
            // At least one template enters wild here — allow wild chars + any literal continuations
            let mut merged = Self::wild_allowed().to_vec();
            for b in &valid {
                if !merged.contains(b) { merged.push(*b); }
            }
            Some(merged)
        } else if valid.is_empty() {
            None // all dead
        } else {
            Some(valid)
        }
    }

    /// Convert to a Constraint for the GPU gate.
    pub fn constraint(&self) -> crate::json_sampler::Constraint {
        match self.valid_next_bytes() {
            None => crate::json_sampler::Constraint::AnyCharacter, // all templates dead
            Some(bytes) if bytes.len() > 100 => crate::json_sampler::Constraint::AnyCharacter, // effectively unconstrained
            Some(bytes) => {
                let mut w = [0u32; 4];
                for b in bytes {
                    if b < 128 {
                        let bit = 1u32 << (b & 31);
                        w[(b >> 5) as usize] |= bit;
                    }
                }
                crate::json_sampler::Constraint::JsonBitmap(w)
            }
        }
    }

    /// Advance by one generated byte.
    pub fn advance(&mut self, b: u8) {
        if self.in_wild {
            // In a free value section — exit when we see closing quote
            if b == b'"' {
                self.in_wild = false;
                self.pos += 1; // skip past the WILD marker
                // Now advance past the `"` in the template too
                // The template has WILD followed by `"` — we consumed `"`, advance
                // Filter alive templates at the new position
                for (i, tmpl) in self.templates.iter().enumerate() {
                    if !self.alive[i] { continue; }
                    // After WILD, the next byte in template should be what follows WILD
                    // We already advanced pos past WILD, check current pos
                    if self.pos < tmpl.len() && tmpl[self.pos] != b'"' {
                        // Mismatch — this template expected something else after the wild value
                        // Actually the `"` closing the value is part of the template text after WILD
                    }
                }
                // The `"` is the closing quote of the value — it's implicit after WILD
                // Templates: ...WILD..."  — the `"` after WILD is in the template
                // We need to skip past it in the template
                self.advance_templates(b);
            }
            return;
        }

        // Check if any alive template has WILD at this position
        for (i, tmpl) in self.templates.iter().enumerate() {
            if !self.alive[i] { continue; }
            if self.pos < tmpl.len() && tmpl[self.pos] == WILD {
                if b == b'"' {
                    // Empty value ("") — closing quote immediately
                    // Skip past WILD and match the closing quote
                    self.pos += 1;
                    self.advance_templates(b);
                } else {
                    // Enter wild mode — this byte is the start of a free value
                    self.in_wild = true;
                    // Don't advance pos — stay at WILD until closing quote
                }
                return;
            }
        }

        self.advance_templates(b);
    }

    fn advance_templates(&mut self, b: u8) {
        for (i, tmpl) in self.templates.iter().enumerate() {
            if !self.alive[i] { continue; }
            if self.pos >= tmpl.len() || tmpl[self.pos] != b {
                self.alive[i] = false;
            }
        }
        self.pos += 1;
    }

    /// Are all templates exhausted?
    pub fn is_done(&self) -> bool {
        self.alive.iter().enumerate().all(|(i, &a)| {
            !a || self.pos >= self.templates[i].len()
        })
    }

    /// Is the FST still active (at least one template alive)?
    pub fn is_active(&self) -> bool {
        self.alive.iter().any(|&a| a)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dispatch_task_prefix() {
        let mut fst = SchemaFST::new();
        let prefix = b"{\"tool\": \"d";
        for &b in prefix {
            assert!(fst.is_active());
            let valid = fst.valid_next_bytes();
            if let Some(ref v) = valid {
                assert!(v.contains(&b), "byte {:?} not in valid {:?} at pos {}", b as char, v, fst.pos);
            }
            fst.advance(b);
        }
        assert!(fst.is_active());
        // After "d", only "ispatch_task" should be alive
        let valid = fst.valid_next_bytes().unwrap();
        assert_eq!(valid, vec![b'i']); // only dispatch_task continues with 'i'
    }

    #[test]
    fn test_create_coder_project_full() {
        let mut fst = SchemaFST::new();
        let full = br#"{"tool": "create_coder_project", "name": "test-proj"}"#;
        for (i, &b) in full.iter().enumerate() {
            let active = fst.is_active();
            let valid = fst.valid_next_bytes();
            eprintln!("pos={} byte={:?} active={} valid={:?} in_wild={}",
                i, b as char, active, valid.as_ref().map(|v| v.len()), fst.in_wild);
            assert!(active, "FST died at pos {} byte {:?}", i, b as char);
            if let Some(ref v) = valid {
                assert!(v.contains(&b), "byte {:?} not in valid {:?} at pos {}", b as char, v, i);
            }
            fst.advance(b);
        }
        eprintln!("final: active={} done={} pos={}", fst.is_active(), fst.is_done(), fst.pos);
        // FST should be active and done (or close to done)
    }

    #[test]
    fn test_create_coder_project_constrains_after_tool() {
        let mut fst = SchemaFST::new();
        // After the tool name, the next bytes should be constrained to `, "name": "`
        let prefix = br#"{"tool": "create_coder_project""#;
        for &b in prefix {
            fst.advance(b);
        }
        assert!(fst.is_active(), "FST should be active after tool name");
        let valid = fst.valid_next_bytes();
        assert!(valid.is_some(), "should be constrained after tool name close quote");
        let v = valid.unwrap();
        assert!(v.contains(&b','), "comma should be valid, got: {:?}", v);
        assert!(!v.contains(&b'}'), "close brace should NOT be valid");
    }

    #[test]
    fn test_blocks_premature_close() {
        let mut fst = SchemaFST::new();
        // Generate {"tool": "dispatch_task",
        let partial = b"{\"tool\": \"dispatch_task\", ";
        for &b in partial {
            fst.advance(b);
        }
        // At this point, } should NOT be in valid bytes — project key is required
        let valid = fst.valid_next_bytes();
        if let Some(v) = valid {
            assert!(!v.contains(&b'}'), "close brace should not be allowed here, valid: {:?}", v);
        }
    }
}
